[package]
name = "otp-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29.1"
egui-file-dialog = "0.7.0"

otp_exchange = { git = "https://github.com/NickyNocerino/otp-exchange.git", branch = "1GB" }

